FROM openjdk:11
LABEL maintainer="javaguides.net"
ADD target/Project-Enterprise-0.0.1-SNAPSHOT.jar Project-Enterprise-0.0.1-SNAPSHOT.jar.original
ENTRYPOINT ["java", "-jar", "Project-Enterprise-0.0.1-SNAPSHOT.jar.original"]
