-- INSERT INTO TUTORIALS (ID, TITLE, DESCRIPTION, PUBLISHED) VALUES (1, 'Software Engineering','dfsdfs', true);
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (1, 'user4', 'user5');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (2, 'admin', 'admin');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (3, 'user1', 'user5');

INSERT INTO COMPANYS (COMPANYS_ID, NAMECOMPANY) VALUES (1, 'Advice');
INSERT INTO COMPANYS (COMPANYS_ID, NAMECOMPANY) VALUES (2, 'jdvice');

INSERT INTO DEPARTMENTS (DEPARTMENTS_ID, NAMEDEPARTMENT,COMPANYS_ID) VALUES (1, 'Marketing',1);
INSERT INTO DEPARTMENTS (DEPARTMENTS_ID, NAMEDEPARTMENT,COMPANYS_ID) VALUES (2, 'garketing',2);







INSERT INTO EMPLOYEES (EMPLOYEE_ID, SURENAME,DEPARTMENTS_ID,EMAIL) VALUES (1, 'user11',1,'asdsd@hhh.com');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, SURENAME,DEPARTMENTS_ID,EMAIL) VALUES (2, 'user12',2,'asdhyyyyd@hhh.com');



