-- INSERT INTO TUTORIALS (ID, TITLE, DESCRIPTION, PUBLISHED) VALUES (1, 'Software Engineering','dfsdfs', true);
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (1, 'user4', 'user5');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (2, 'admin', 'admin');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (3, 'user1', 'user5');








INSERT INTO EMPLOYEES (EMPLOYEE_ID, SURENAME) VALUES (1, 'user11');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, SURENAME) VALUES (2, 'user12');
INSERT INTO DEPARTMENTS (DEPARTMENTS_ID, NAMEDEPARTMENT) VALUES (1, 'Marketing');
INSERT INTO DEPARTMENTS (DEPARTMENTS_ID, NAMEDEPARTMENT) VALUES (2, 'garketing');
INSERT INTO COMPANYS (COMPANYS_ID, NAMECOMPANY,EMAIL) VALUES (1, 'Advice','asdsd@hhh.com');
INSERT INTO COMPANYS (COMPANYS_ID, NAMECOMPANY,EMAIL) VALUES (2, 'jdvice','asdhyyyyd@hhh.com');