-- INSERT INTO TUTORIALS (ID, TITLE, DESCRIPTION, PUBLISHED) VALUES (1, 'Software Engineering','dfsdfs', true);
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (1, 'user4', 'user5');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (2, 'admin', 'admin');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, SURENAME,IDS) VALUES (1, 'user11',1);