-- INSERT INTO TUTORIALS (ID, TITLE, DESCRIPTION, PUBLISHED) VALUES (1, 'Software Engineering','dfsdfs', true);
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (1, 'user4', 'user5');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (2, 'admin', 'admin');
INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (3, 'user1', 'user5');

INSERT INTO COMPANYS (COMPANYS_ID, NAMECOMPANY) VALUES (1, 'Advice');
INSERT INTO COMPANYS (COMPANYS_ID, NAMECOMPANY) VALUES (2, 'Banana');
INSERT INTO COMPANYS (COMPANYS_ID, NAMECOMPANY) VALUES (3, 'Msi');

INSERT INTO DEPARTMENTS (DEPARTMENTS_ID, NAMEDEPARTMENT,COMPANYS_ID) VALUES (1, 'Marketing',1);
INSERT INTO DEPARTMENTS (DEPARTMENTS_ID, NAMEDEPARTMENT,COMPANYS_ID) VALUES (2, 'Accounting/Finance',2);
INSERT INTO DEPARTMENTS (DEPARTMENTS_ID, NAMEDEPARTMENT,COMPANYS_ID) VALUES (3, 'HR',3);






INSERT INTO EMPLOYEES (EMPLOYEE_ID, SURENAME,DEPARTMENTS_ID,EMAIL) VALUES (1, 'Jirawat Ratsamee',1,'6331305002@lamduan.mfu.ac.th');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, SURENAME,DEPARTMENTS_ID,EMAIL) VALUES (2, 'Chindanai  Potijuntajinda',2,'6331305007@lamduan.mfu.ac.th');
INSERT INTO EMPLOYEES (EMPLOYEE_ID, SURENAME,DEPARTMENTS_ID,EMAIL) VALUES (3, 'Sai Reacky',3,'6331305048@lamduan.mfu.ac.th');



